config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', 
                                       :omniauth_callbacks => "omniauth_callbacks" }
  root 'store#index', as: 'store'


  resources :tvshows
  resources :moods
  resources :users, only: [:show, :index]
  resources :playlists
  resources :showlines, only: [:create]
  resources :orders, only: [:show]


  resources :users do
    resources :playlists
  end

  resources :moods do
    resources :tvshows
  end

  namespace :admin do
    resources :stats, only: [:index]
  end

  post 'playlists/:id/submit', to: 'playlists#submit', as: 'submit'
  post 'tvshows/:id', to: 'tvshows#edit', as: 'edit'

  get '/users/sign_out', to: 'store#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :playlists
  belongs_to :current_playlist, :class_name => "Playlist"

  def create_current_playlist
    new_playlist = playlists.create()
    self.current_playlist_id = new_playlist.id    
    save
  end

  def remove_cart

    self.current_playlist_id = nil
    save
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name  
    end
  end

   def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end
  
  def show
  	@user = User.find(params[:id])
  end

end

app/views/users/index.html.erb
<% if user_signed_in? %>
	<h2>User </h2>
	<% @users.each do |user| %>
	  <p><%= link_to user.name, user_path(user) %> | 
	  	Happiness Level: <%= user.happiness %> | 
	  	Free Time: <%= user.free_time %> hours | 
	  
	  </p>  
	<% end %>
<% else %> 
	You don't have access to view this page. 
	
<% end %> 

app/views/users/show.html.erb
<ul>

<% if current_user.id == params[:id].to_i %>
	<h2>Name: <%= current_user.name %> </h2>
	<p>Happiness Level: <%= current_user.happiness %> </p>
	<p>Free Time: <%= current_user.free_time %> hours </p>	
	<ul> 
<% current_user.playlists.each do |p| %>
	
		<li><strong> Playlist Created At: <%= link_to "#{p.created_at}",  user_playlist_path(current_user, p) %> </li>
	
<% end %>
<ul> 

</ul>
<% else %>
	You don't have access to view this page
<% end %>