config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', 
                                       :omniauth_callbacks => "omniauth_callbacks" }
  root 'store#index', as: 'store'


  resources :tvshows
  resources :moods
  resources :users, only: [:show, :index]
  resources :playlists
  resources :showlines, only: [:create]
  resources :orders, only: [:show]


  resources :users do
    resources :playlists
  end

  resources :moods do
    resources :tvshows
  end

  namespace :admin do
    resources :stats, only: [:index]
  end

  post 'playlists/:id/submit', to: 'playlists#submit', as: 'submit'
  post 'tvshows/:id', to: 'tvshows#edit', as: 'edit'

  get '/users/sign_out', to: 'store#index'

end

app/models/tvshow.rb
#create_table "tvshows", force: :cascade do |t|
#  t.string   "title"
#  t.integer  "suspense_level"
#  t.integer  "time_commitment"
#  t.integer  "price"
#  t.integer  "mood_id"
#  t.datetime "created_at",  null: false
#  t.datetime "updated_at",  null: false
#end

class Tvshow < ActiveRecord::Base
  has_many :mood_shows
  has_many :moods, through: :mood_shows
  has_many :showlines

  validates :title, :suspense_level, :time_commitment, :price, presence: true

  



end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
 

  def index
    @tvshows = Tvshow.all    
  end
  
  def show
    @tvshow = Tvshow.find(params[:id])
  end

  def new
    @mood = Mood.find(params[:mood_id])
    @tvshow = Tvshow.new

  end


  def edit 
   @tvshow = Tvshow.find(params[:id])
  end

  def create    
    @mood = Mood.find(params[:mood_id])
    @tvshow = @mood.tvshows.build(tvshow_params)      
    @mood.save
    
    respond_to do |format| 
      if @tvshow.save      
        format.json {render json: @tvshow}
        format.html { redirect_to @tvshow, notice: 'TV show was successfully created.' }
      else
        render "tvshow/show", notice: 'could not add TV show'
      end
    end
  end


  def destroy   
     @tvshow = Tvshow.find(params[:id])
     @tvshow.destroy
     redirect_to store_path, status: 303
  end

  def update
    @tvshow = Tvshow.find(params[:id])
    respond_to do |format|
      if @tvshow.update(tvshow_params)
        format.html { redirect_to @tvshow, notice: 'Tv Show was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  private
  def tvshow_params
      params.require(:tvshow).permit( 
        :id, 
        :title,
        :suspense_level,
        :time_commitment,
        :price,        
        :mood_ids
      )
    end

end

app/views/tvshows/_index.html.erb
<br /> 
<div class="ashow">
<% @tvshows.each do |tvshow| %>
  <div>
    <p>
      <%= link_to tvshow.title, tvshow_path(tvshow) %>
       || 
      $<%= tvshow.price.to_f/100 %> |
      <strong>time:</strong>  <%= tvshow.time_commitment %> hours |
      <strong> suspense-level:</strong> <%= tvshow.suspense_level %> |
      <br /> 
      <% if user_signed_in? %>
        <%= button_to 'Add to Playlist', showlines_path(tvshow_id: tvshow) %>
        <button id="delete" data-url="<%= tvshow_path(tvshow) %>" data-method="DELETE">Delete</button>
        **<%= link_to 'Edit', tvshow, :method => :edit  %>**
      <% end %>
    </p>
  </div>
<% end %>


 </div>

app/views/tvshows/_item.html.erb
<p><%= item.title %> | <%= number_to_currency(to_currency(item.price)) %>
<% if user_signed_in? %>
  | <%= button_to 'Add to Cart', line_items_path(item_id: item) %>
<% end%>
</p>

app/views/tvshows/_item_link.html.erb
 <p><%= item.title %> | $<%= item.price.to_f/100 %> | <%= button_to 'Add to Cart', line_items_path(item_id: item) %></p>

app/views/tvshows/edit.html.erb
<%= form_for(@tvshow) do |f| %>

  <div class="field"> <%= f.label :title %><br>
  <%= f.text_field :title %></div>

  <div class="field"><%= f.label :suspense_level %><br>
  <%= f.number_field :suspense_level %></div>

  <div class="field"><%= f.label :time_commitment %><br>
  <%= f.number_field :time_commitment %></div>

  <div class="field"><%= f.label :price %><br>
  <%= f.number_field :price %></div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tvshows/index.html.erb
<%= render 'tvshows/index', locals: {tvshows: @tvshows} %>

app/views/tvshows/new.html.erb
<br />

<h3> New TV Show for Mood <%= @mood.title %>  </h3>
<%= form_for(@tvshow) do |f| %>

  <div class="field"> <%= f.label :title %><br>
  <%= f.text_field :title %></div>

  <div class="field"><%= f.label :suspense_level %><br>
  <%= f.number_field :suspense_level %></div>

  <div class="field"><%= f.label :time_commitment %><br>
  <%= f.number_field :time_commitment %></div>

  <div class="field"><%= f.label :price %><br>
  <%= f.number_field :price %></div>


  <div class="field">
    <%= f.hidden_field :mood_ids, :value => @mood.id %>
  </div>

  <br>
  
  <div class="actions"><%= f.submit 'Submit', :class => 'btn btn-primary' %></div>

<% end %>
</div> 

app/views/tvshows/show.html.erb
<h1>Title: <%= @tvshow.title %></h1>
<p>Price: $ <%= @tvshow.price.to_f/100 %></p>
<p>Suspense Level: <%= @tvshow.suspense_level %></p>
<h2>Length: <%= @tvshow.time_commitment %> hours </p>
	<% if !@tvshow.moods.empty? %>
		
		Mood: <% @tvshow.moods.each do |m| %>
		<%= link_to "#{m.title}", mood_path(m) %> 
	<% end %> 
<% end %>