config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', 
                                       :omniauth_callbacks => "omniauth_callbacks" }
  root 'store#index', as: 'store'


  resources :tvshows
  resources :moods
  resources :users, only: [:show, :index]
  resources :playlists
  resources :showlines, only: [:create]
  resources :orders, only: [:show]


  resources :users do
    resources :playlists
  end

  resources :moods do
    resources :tvshows
  end

  namespace :admin do
    resources :stats, only: [:index]
  end

  post 'playlists/:id/submit', to: 'playlists#submit', as: 'submit'
  post 'tvshows/:id', to: 'tvshows#edit', as: 'edit'

  get '/users/sign_out', to: 'store#index'

end

app/models/playlist.rb
#create_table "playlists", force: :cascade do |t|
#    t.integer  "user_id"
#    t.string   "status",     default: "not submitted"
#    t.datetime "created_at",                           null: false
#    t.datetime "updated_at",                           null: false
#  end


class Playlist < ActiveRecord::Base
  has_many :showlines
  has_many :tvshows, through: :showlines
  belongs_to :user

  

  def tvshows_attributes=(tvshow)   
    self.tvshow = Tvshow.find_or_create_by(title: tvshow.title)
    self.tvshow.update(tvshow)
  end
  
  def save_show(tvshow_id)
    showline=self.showlines.build(tvshow_id: tvshow_id)
    showline
  end


  def add_tvshow(tvshow_id)
    showline = self.showlines.find_by(tvshow_id: tvshow_id)
    enough_time, enough_emotional_capital = meet_requirements(tvshow_id)

    if showline
      "You have already added this tv show."
    else
      if enough_time && enough_emotional_capital          
        "successfully added tv show"
      elsif enough_time && !enough_emotional_capital
        "Sorry. " + emotional_issue
      elsif enough_emotional_capital && !enough_time
        "Sorry. " + time_issue
      else
        "Sorry. " + emotional_issue + " and " + time_issue
      end
    end
  end

  #total for all shows...
  def total
    total = 0
    if self.showlines      
      self.showlines.each do |showline|
        total += showline.tvshow.price
      end    
    end    
    return total
  end

  def total_suspense(tvshow_id)
    tvshow = Tvshow.find_by(id: tvshow_id)
    s_total = 0
    if self.showlines      
      self.showlines.each do |showline|
        s_total += showline.tvshow.suspense_level
      end    
    end    
    s_total += tvshow.suspense_level
    return s_total
  end

  def total_suspense_view    
    s_total = 0
    if self.showlines      
      self.showlines.each do |showline|
        s_total += showline.tvshow.suspense_level
      end    
    end        
    return s_total
  end

  def total_time(tvshow_id)
    tvshow = Tvshow.find_by(id: tvshow_id)
    time_total = 0
    if self.showlines       
      self.showlines.each do |showline|        
        time_total += showline.tvshow.time_commitment
      end    
    end
    time_total += tvshow.time_commitment         
    return time_total 
  end

  def total_time_view 
    time_total = 0
    if self.showlines       
      self.showlines.each do |showline|        
        time_total += showline.tvshow.time_commitment
      end    
    end
    return time_total 
  end

  

  def submit_list      
    user.remove_cart
  end

  def change_attributes
    update(status: 'submitted')
      new_happiness = self.user.happiness - total_suspense_view
      new_free_time = self.user.free_time - total_time_view
      self.user.update(
        :happiness => new_happiness,
        :free_time => new_free_time
      )
    
  end

  def meet_requirements(tvshow_id)    
    enough_time, enough_emotional_capital = false
    if user.free_time >= total_time(tvshow_id)
      enough_time = true
    end
    
    if user.happiness >= total_suspense(tvshow_id)
      enough_emotional_capital = true
    end
    
    return [enough_time, enough_emotional_capital]

  end

  def time_issue    
    "You do not have enough time to watch this show."
  end

  def emotional_issue    
    "Watching this show will stress you out too much."
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
    @playlists = Playlist.all
  end

  def new 
    @playlist = Playlist.new
    @tvshow = Tvshow.new
  end
  
  def show
    @playlist = Playlist.find(params[:id])
    
  end

  def submit
    playlist = Playlist.find(params[:id])
    playlist.change_attributes
    playlist.submit_list
    redirect_to playlist_path(playlist)
  end

  private 

  
  def playlist_params
   params.require(:playlist).permit(tvshows_attributes: [:id, :title, :suspense_level, :time_commitment])

  end
end

app/views/playlists/_playlist.html.erb
<h2>Playlist Created <%=playlist.created_at.strftime("%c")%></h2>

<% playlist.showlines.each do |showline| %>	
  <p><%= link_to showline.tvshow.title, tvshow_path(showline.tvshow) %> | <%= number_to_currency(to_currency(showline.tvshow.price)) %> | Suspense: <%= showline.tvshow.suspense_level %> | 
  Time Commitment: <%= showline.tvshow.time_commitment %> hours
  </p>  
<% end %>

<p>Order total: <strong><%= number_to_currency(to_currency(playlist.total)) %></strong> </p>

<%= button_to 'Submit', submit_path(playlist) if playlist.status != "submitted" %>

app/views/playlists/index.html.erb
<h1>Your Playlists</h1>

<%= render @playlists %>

app/views/playlists/new.html.erb
<%= form_for @playlist do |f| %>
  <h2>Playlists</h2>
   
  <ul>
    <%= f.fields_for :tvshow do |tvshows_form| %>

      <li>
        <%= tvshows_form.label :title %>
        <%= tvshows_form.text_field :title %>
 	    </li>
 	    <li>
        <%= tvshows_form.label :suspense_level %>
        <%= tvshows_form.number_field :suspense_level %>
      </li>
      <li>
        <%= tvshows_form.label :time_commitment %>
        <%= tvshows_form.number_field :time_commitment %>
      </li>
      <li>
        <%= tvshows_form.label :price %>
        <%= tvshows_form.number_field :price %>		        
      </li>
    <% end %>
  </ul>
  	<%= f.submit %>
<% end %>


 

app/views/playlists/show.html.erb
<h1>Your Playlist</h1>

<% if notice %>
  <p><%= notice %></p>
<% end %>


<% if @message %>
  <div class="center alert">
    <p><%= @message %></p>
  </div>
<% end %>

<% @playlist.showlines.each do |showline| %>
  
  <p><%= link_to showline.tvshow.title, tvshow_path(showline.tvshow) %> | 
  	$<%= showline.tvshow.price.to_f/100 %> | Suspense Level: <%= showline.tvshow.suspense_level %> | 
  	 Time Commitment: <%= showline.tvshow.time_commitment %> hours | 
  	
<% end %>

<p>Playlist Summary: <p>
	<p><strong>Total Price: $<%= @playlist.total.to_f/100 %></strong> </p>
	<p><strong>Total Time: <%= @playlist.total_time_view %></strong> </p>
	<p><strong>Total Suspense: <%= @playlist.total_suspense_view %></strong> </p>
<% if @playlist.status == 'not submitted' %>
  <%= button_to 'Submit', submit_path %>
<% end %>