config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', 
                                       :omniauth_callbacks => "omniauth_callbacks" }
  root 'store#index', as: 'store'


  resources :tvshows
  resources :moods
  resources :users, only: [:show, :index]
  resources :playlists
  resources :showlines, only: [:create]
  resources :orders, only: [:show]


  resources :users do
    resources :playlists
  end

  resources :moods do
    resources :tvshows
  end

  namespace :admin do
    resources :stats, only: [:index]
  end

  post 'playlists/:id/submit', to: 'playlists#submit', as: 'submit'
  post 'tvshows/:id', to: 'tvshows#edit', as: 'edit'

  get '/users/sign_out', to: 'store#index'

end

app/views/layouts/_header.html.erb
    <ul class="nav navbar-nav">

  		 <li> <%= link_to "PLAYLISTER HOME", store_path %> </li>
       <% if current_user %> 
          <% if current_user.current_playlist %> 
            <li> <%= link_to "Current Playlist", playlist_path(current_user.current_playlist) %> </li>       
          <% end %> 
        
            <li> <%= link_to "Your Profile", user_path(current_user) %> </li>
            <li> <%= link_to "All of Your Playlists", user_playlists_path(current_user) %> </li>
            <li> <%= link_to "Add a New Mood", new_mood_path %> </li>
             <li> <%= link_to "Stats", admin_stats_path %> </li>

       	    
        
        
         
        
      <% end %> 
  		
  			
       	
        <%= render 'layouts/nav_links_for_auth' %>
        
    </ul>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Playlister </title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
    
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
</head>
<body>

 <!--  navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>      
        </div>
        

        <div class="navbar-collapse collapse">

			<%= render 'layouts/header' %>
			
		</div>
	  </div>
	</div>
	<div class="container"  role="main">
  <%= render 'layouts/messages' %> 
		<% if user_signed_in? %>
			Signed in as <%= current_user.email %> 
		<% end %>
		<br> 
      <%= yield %>
    </div>


</body>
</html>